[package]
name = "executor"
version = "0.1.6"
edition = "2021"
publish = false

[dependencies]
quickfix = "0.2.0"
quickfix-msg40 = "0.2.0"
quickfix-msg41 = "0.2.0"
quickfix-msg42 = "0.2.0"
thiserror = "2.0.11"
